In [1]:
import tensorflow as tf

In [19]:
zero_tsr = tf.zeros([3,2])
ones_tsr = tf.ones([3,2])
filled_tsr = tf.fill([3,2],42)

# Create tensor out of existing constant
constant_tsr = tf.constant([1,2,3])

# Must be initialized in order, since they rely on previous tensors
zeros_similar = tf.zeros_like(constant_tsr)
ones_similar = tf.ones_like(constant_tsr)

# tensor resulting in [0.0,0.5,1.0]
linear_tsr = tf.linspace(start=0.0,stop=1.0,num=3)

# tensor resulting in [6,9,12]
integer_seq_tsr = tf.range(start=6,limit=15,delta=3)

# tensor resulting in random numbers with uniform distribution between 0 and 1, minval <= X < maxval
randunif_tsr = tf.random_uniform([3,2],minval=0,maxval=1)

# tensor with random draw from normal distribution
randnorm_tsr = tf.random_normal([3,2],mean=0.0,stddev=1.0)

# Always picks normal values within 2 std devs
runcnorm_tsr = tf.truncated_normal([3,2],mean=0.0,stddev=1.0)

# Randomize entries of arrays
crop_size = [2,1]
shuffled_output = tf.random_shuffle(filled_tsr)
cropped_output = tf.random_crop(filled_tsr,crop_size)

# Randomly crop an image of size (height, weight, 3
# cropped_image = tf.random_crop(my_image, [height/2,width/2,3])

In [20]:
# After creating tensors, create corresponding variables by wrapping tensor in variable function
my_var = tf.Variable(tf.zeros([3,2]))

In [21]:
# Variables are parameters of algorithm, TF keeps track of how to change them to optimize algorithm
# Placeholders are objects you use to feed in data of specific type and shape
# Initializing puts it on the computational graph
my_var = tf.Variable(tf.zeros([3,2]))
sess = tf.Session()
initialize_op = tf.global_variables_initializer()
sess.run(initialize_op)

In [22]:
# Placeholders get data from feed_dict argument in the session
import numpy as np
sess = tf.Session()
x = tf.placeholder(tf.float32,shape=[2,2])
y = tf.identity(x)
x_vals = np.random.rand(2,2)

# y is the operation that will be run, feed_dict feeds x_vals into placebolder x
sess.run(y,feed_dict={x:x_vals})

array([[0.7961337 , 0.10480129],
       [0.30529642, 0.22791238]], dtype=float32)

In [23]:
# Need to tell TF when to initialize variables
initialize_op = tf.global_variables_initializer()

# To initialize based on results of initializing another variable, must initialize in order
sess = tf.Session()
first_var = tf.Variable(tf.zeros([3,2]))
sess.run(first_var.initializer)
second_var = tf.Variable(tf.zeros_like(first_var))
sess.run(second_var.initializer)

In [24]:
iden_matrix = tf.diag([1.0,1.0,1.0])
A = tf.truncated_normal([2,3])
B = tf.fill([2,3],5.0)
C = tf.random_uniform([3,2])
D = tf.convert_to_tensor(np.array([[1.0,2.0,3.0],[-3.0,-7.0,-1.0],[0.0,5.0,-2.0]]))

In [25]:
print(sess.run(iden_matrix))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:
print(sess.run(A))

[[-1.104158    0.75994706  1.9520531 ]
 [-1.2386881  -1.0494369  -0.01560644]]


In [27]:
print(sess.run(B))

[[5. 5. 5.]
 [5. 5. 5.]]


In [28]:
print(sess.run(C))

[[0.5574429  0.9544358 ]
 [0.51281965 0.23435628]
 [0.24480581 0.9201859 ]]


In [29]:
print(sess.run(D))

[[ 1.  2.  3.]
 [-3. -7. -1.]
 [ 0.  5. -2.]]


In [30]:
print(sess.run(A+B))

[[5.007455  4.039192  6.540644 ]
 [6.1329594 5.0703993 4.790745 ]]


In [31]:
print(sess.run(tf.matmul(B,iden_matrix)))

[[5. 5. 5.]
 [5. 5. 5.]]


In [32]:
print(sess.run(tf.transpose(C)))

[[0.37161672 0.16318083 0.8678353 ]
 [0.08664322 0.54044306 0.9985126 ]]


In [33]:
print(sess.run(tf.matrix_determinant(D)))

-38.0


In [34]:
print(sess.run(tf.matrix_inverse(D)))

[[-0.5        -0.5        -0.5       ]
 [ 0.15789474  0.05263158  0.21052632]
 [ 0.39473684  0.13157895  0.02631579]]


In [36]:
# Cholesky decomposition
print(sess.run(tf.cholesky(iden_matrix)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [37]:
# For eigenvalues and eigenvectors, use:
# Outputs eigenvalues in the first row, and eigenvectors in the remaining vectors
print(sess.run(tf.self_adjoint_eig(D)))

(array([-10.65907521,  -0.22750691,   2.88658212]), array([[ 0.21749542,  0.63250104, -0.74339638],
       [ 0.84526515,  0.2587998 ,  0.46749277],
       [-0.4880805 ,  0.73004459,  0.47834331]]))


In [41]:
print(sess.run(tf.div(3,4)))
print(sess.run(tf.truediv(3,4)))
print(sess.run(tf.floordiv(3.0,4.0)))
print(sess.run(tf.mod(22.0,5.0)))

0
0.75
0.0
2.0


In [54]:
# Activation functions live in the neural network (nn) library in tf

# ReLU
print('\n',sess.run(tf.nn.relu([-3.0,3.0,10])))

# ReLU6 caps the linearly increasing part at 6
print('\n',sess.run(tf.nn.relu6([-3.0,3.0,10])))

# Sigmoid function
print('\n',sess.run(tf.nn.sigmoid([-1.0,0.0,1.0])))

# Hyper tangent, same as Sigmoid, but goes from -1 to 1 instead of 0 to 1
print('\n',sess.run(tf.nn.tanh([-1.0,0.0,1.0])))

# softsign: x / (abs(x) + 1)
print('\n',sess.run(tf.nn.softsign([-1.0,0.0,1.0])))

# softplus: log(exp(x) + 1)
print('\n',sess.run(tf.nn.softplus([-1.0,0.0,1.0])))

# same as softplus, but bottom asymptote is -1 instead of 0
print('\n',sess.run(tf.nn.elu([-1.0,0.0,1.0])))


 [ 0.  3. 10.]

 [0. 3. 6.]

 [0.26894143 0.5        0.7310586 ]

 [-0.7615942  0.         0.7615942]

 [-0.5  0.   0.5]

 [0.31326166 0.6931472  1.3132616 ]

 [-0.63212055  0.          1.        ]
